### ISSUE TITLE
/servermanager.sh: line 37: ./PalServer.sh: No such file or directory

### ISSUE THREAD

**Issue by Tripp024** [jammsen/docker-palworld-dedicated-server#2]
At first I got the problem from the other issue but that seems to be fixed. Now I'm getting this error: /servermanager.sh: line 37: ./PalServer.sh: No such file or directory

Thanks for creating this Docker container though :)

### Software setup

- OS: Fedora Server

Edit: 
Fixed by running this command: chown -R 1000:1000 game/ 
(thanks, @Lexiv)
Also, change the ports section to this so you can connect:
ports:
      - "8211:8211/udp"

**Comment by LitchiInn** [comment]
maybe fixed by [this commit](https://github.com/jammsen/docker-palworld-dedicated-server/commit/0e051d5c4fe3e4ba960c2be36e507d3a550e2a36)

**Comment by JohnCido** [comment]
Same issue here

**Comment by JohnCido** [comment]
> maybe fixed by [this commit](https://github.com/jammsen/docker-palworld-dedicated-server/commit/0e051d5c4fe3e4ba960c2be36e507d3a550e2a36)

And since I'm using the latest image from hub I guess this commit did not fix it.

**Comment by Doomgull** [comment]
https://github.com/jammsen/docker-palworld-dedicated-server/issues/1#issuecomment-1900630342

**Comment by Tripp024** [comment]
Fixed by running this command: chown -R 1000:1000 game/
Also, change the ports section to this so you can connect:
ports:
- "8211:8211/udp"

**Comment by Tripp024** [comment]
Fixed by running this command: chown -R 1000:1000 game/
Also, change the ports section to this so you can connect:
ports:

    "8211:8211/udp"

**Comment by jammsen** [comment]
Please see #1 
This is dublicate content, im closing this in favor to only keep 1 ticket up-to-date, but thanks for reporting!
